services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"

  cactus-bot:
    image: docker-cactus-bot
 
volumes:
  pgdata: